/*
same name client control 
remove added member from combobox
enable false all buttons before start
 */
package game;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maya
 */
public class app extends javax.swing.JFrame {

    public static app thisApp;
    //controling comboBox
    public boolean addingEvent;
    /**
     * Creates new form app
     */
    // all table models
    public DefaultListModel listModel = new DefaultListModel();
    public DefaultListModel listMygroupsMemberModel = new DefaultListModel();
    public DefaultTableModel tblBillsModel = new DefaultTableModel();
    public DefaultTableModel tblRecivedBillsModel = new DefaultTableModel();
    public DefaultTableModel tblMyBillsDetailModel = new DefaultTableModel();
    public DefaultTableModel tblHomeMsgsModel = new DefaultTableModel();
    

    public app() {
        initComponents();
        // comboBox settings
        cmbAddtoGroup.removeAllItems();
        cmbMygroubs.removeAllItems();
        cmbMyBillsgroubs.removeAllItems();
        cmbRecivedBillsgroubs.removeAllItems();

        cmbGroups.removeAllItems();
        cmbAddtoGroup.setSelectedIndex(-1);
        cmbMygroubs.setSelectedIndex(-1);
        cmbMyBillsgroubs.addItem("All");
        cmbRecivedBillsgroubs.addItem("All");
        listGroupMembers.setModel(listModel);
        listMygroupsMember.setModel(listMygroupsMemberModel);
        //tblHomeMsgs table settings
         tblHomeMsgs.setModel(tblHomeMsgsModel);
        tblHomeMsgs.setRowHeight(30);
        tblHomeMsgsModel.setColumnIdentifiers(new Object[]{"Recent activity"});
        ///tblBills table settings
        tblBills.setModel(tblBillsModel);
        tblBills.setRowHeight(30);
        tblBillsModel.setColumnIdentifiers(new Object[]{"Paid By", "Total", "Description", "group name", "group members", "id", "unpaid"});

        /// tblRecivedBills table settings
        tblRecivedBills.setModel(tblRecivedBillsModel);
        tblRecivedBills.setRowHeight(30);
        tblRecivedBillsModel.setColumnIdentifiers(new Object[]{"Paid By", "Total", "Description", "group name", "group members", "id", "unpaid", "is paid"});

        /// tblMyBillsDetail table settings
        tblMyBillsDetail.setModel(tblMyBillsDetailModel);
        tblMyBillsDetail.setRowHeight(30);
        tblMyBillsDetailModel.setColumnIdentifiers(new Object[]{"Paid By", "Total", "is paid"});

        addingEvent = false;
        thisApp = this;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelHome = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHomeMsgs = new javax.swing.JTable();
        panelGroup = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtGroupName = new javax.swing.JTextField();
        cmbAddtoGroup = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnMakeGroup = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listGroupMembers = new javax.swing.JList<>();
        panelBill = new javax.swing.JPanel();
        cmbGroups = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBillAmount = new javax.swing.JTextField();
        txtBillDescription = new javax.swing.JTextField();
        btnSendBill = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmbMygroubs = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listMygroupsMember = new javax.swing.JList<>();
        panelMybills = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBills = new javax.swing.JTable();
        cmbMyBillsgroubs = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblMyBillsDetail = new javax.swing.JTable();
        btmMarkAsPaid = new javax.swing.JButton();
        panelMybills1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblRecivedBills = new javax.swing.JTable();
        cmbRecivedBillsgroubs = new javax.swing.JComboBox<>();
        lblUserName = new javax.swing.JLabel();
        lblUserName1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        panelHome.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        btnStart.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        txtName.setText("User1");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        tblHomeMsgs.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        tblHomeMsgs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHomeMsgs);

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(txtName))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Home", panelHome);

        panelGroup.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setText("   Group Name : ");

        txtGroupName.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        txtGroupName.setText("home");

        cmbAddtoGroup.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        cmbAddtoGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAddtoGroup.setSelectedIndex(-1);
        cmbAddtoGroup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAddtoGroupItemStateChanged(evt);
            }
        });
        cmbAddtoGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAddtoGroupActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel2.setText("Add Person");

        btnMakeGroup.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        btnMakeGroup.setText("Save");
        btnMakeGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeGroupActionPerformed(evt);
            }
        });

        listGroupMembers.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        listGroupMembers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listGroupMembers);

        javax.swing.GroupLayout panelGroupLayout = new javax.swing.GroupLayout(panelGroup);
        panelGroup.setLayout(panelGroupLayout);
        panelGroupLayout.setHorizontalGroup(
            panelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGroupLayout.createSequentialGroup()
                .addGroup(panelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGroupLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(panelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbAddtoGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelGroupLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelGroupLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnMakeGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        panelGroupLayout.setVerticalGroup(
            panelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGroupLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAddtoGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMakeGroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add  group", panelGroup);

        panelBill.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        cmbGroups.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        cmbGroups.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGroupsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel3.setText("Group Name");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel4.setText("Description");

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel5.setText("Amount");

        txtBillAmount.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        txtBillAmount.setText("200");

        txtBillDescription.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        txtBillDescription.setText("Elektrik");
        txtBillDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBillDescriptionActionPerformed(evt);
            }
        });

        btnSendBill.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        btnSendBill.setText("Send");
        btnSendBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBillLayout = new javax.swing.GroupLayout(panelBill);
        panelBill.setLayout(panelBillLayout);
        panelBillLayout.setHorizontalGroup(
            panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillLayout.createSequentialGroup()
                .addGroup(panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBillLayout.createSequentialGroup()
                        .addGroup(panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBillDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBillLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(txtBillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(512, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBillLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSendBill, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        panelBillLayout.setVerticalGroup(
            panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGroups))
                .addGap(18, 18, 18)
                .addGroup(panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBillDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBillAmount))
                .addGap(75, 75, 75)
                .addComponent(btnSendBill)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add bill", panelBill);

        jPanel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        cmbMygroubs.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        cmbMygroubs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMygroubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMygroubsActionPerformed(evt);
            }
        });

        listMygroupsMember.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        listMygroupsMember.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listMygroupsMember);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbMygroubs, 0, 216, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(787, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(cmbMygroubs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Groups", jPanel1);

        panelMybills.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        tblBills.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        tblBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBillsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblBills);

        cmbMyBillsgroubs.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        cmbMyBillsgroubs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMyBillsgroubs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMyBillsgroubsItemStateChanged(evt);
            }
        });
        cmbMyBillsgroubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMyBillsgroubsActionPerformed(evt);
            }
        });

        tblMyBillsDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblMyBillsDetail);

        btmMarkAsPaid.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        btmMarkAsPaid.setText("mark  as  paid");
        btmMarkAsPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmMarkAsPaidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMybillsLayout = new javax.swing.GroupLayout(panelMybills);
        panelMybills.setLayout(panelMybillsLayout);
        panelMybillsLayout.setHorizontalGroup(
            panelMybillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMybillsLayout.createSequentialGroup()
                .addComponent(cmbMyBillsgroubs, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(791, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
            .addComponent(jScrollPane6)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMybillsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btmMarkAsPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMybillsLayout.setVerticalGroup(
            panelMybillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMybillsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbMyBillsgroubs, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btmMarkAsPaid)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My Bills", panelMybills);

        panelMybills1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        tblRecivedBills.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        tblRecivedBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblRecivedBills);

        cmbRecivedBillsgroubs.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        cmbRecivedBillsgroubs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRecivedBillsgroubs.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbRecivedBillsgroubsItemStateChanged(evt);
            }
        });
        cmbRecivedBillsgroubs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbRecivedBillsgroubsMouseClicked(evt);
            }
        });
        cmbRecivedBillsgroubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRecivedBillsgroubsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMybills1Layout = new javax.swing.GroupLayout(panelMybills1);
        panelMybills1.setLayout(panelMybills1Layout);
        panelMybills1Layout.setHorizontalGroup(
            panelMybills1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
            .addGroup(panelMybills1Layout.createSequentialGroup()
                .addComponent(cmbRecivedBillsgroubs, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMybills1Layout.setVerticalGroup(
            panelMybills1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMybills1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbRecivedBillsgroubs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Recived Bills", panelMybills1);

        lblUserName.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        lblUserName1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lblUserName1.setText("User name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// groupName used for filtering results

    public void FillMyBillsTable(String groupName) {
        //according to filtering info (group name ) fill Bilss table
        try {
            tblBillsModel.setRowCount(0);

            if (groupName.equals("All")) {

                for (Bill sendedBill : Client.sendedBills) {

                    tblBillsModel.addRow(new Object[]{sendedBill.sender, sendedBill.amount, sendedBill.description, sendedBill.reciver.name, sendedBill.reciver.members.size(),
                        sendedBill.id, 0});
                }
            } else {

                for (Bill sendedBill : Client.sendedBills) {
                    if (sendedBill.reciver.name.equals(groupName)) {
                        tblBillsModel.addRow(new Object[]{sendedBill.sender, sendedBill.amount, sendedBill.description, sendedBill.reciver.name, sendedBill.reciver.members.size(),
                            sendedBill.id, 0});
                    }
                }
            }
        } catch (Exception e) {
            // when there is no bills do nothing
        }
    }
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

        // coonect client to server
        btnStart.setEnabled(false);
        txtName.setEnabled(false);
        Client.Start("127.0.0.1", 2000);
        lblUserName.setText(txtName.getText());
        //
        tblHomeMsgsModel.addRow(new Object[]{txtName.getText()+"  you are connected"});
        //send msg to server with cleint name
        Message msg = new Message(Message.Message_Type.Name);
        msg.content.add(txtName.getText());
        Client.Send(msg);

    }//GEN-LAST:event_btnStartActionPerformed

    private void cmbAddtoGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAddtoGroupActionPerformed

        //this event triggered if elemnet is selected or if an elemnt is added to combobox list
        // so add the element to the list only if user select element
        if (cmbAddtoGroup.getSelectedIndex() != -1 && !addingEvent) {
            addingEvent = false;
            listModel.addElement((String) cmbAddtoGroup.getSelectedItem());
            cmbAddtoGroup.removeItemAt(cmbAddtoGroup.getSelectedIndex());
        }


    }//GEN-LAST:event_cmbAddtoGroupActionPerformed

    private void cmbAddtoGroupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAddtoGroupItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbAddtoGroupItemStateChanged

    private void btnMakeGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeGroupActionPerformed
        // at least unique group name and one member must be found
        boolean existedName = false;
        for (Group groub : Client.groubs) {
            if (groub.name.equals(txtGroupName.getText())) {
                existedName = true;
                JOptionPane.showMessageDialog(panelHome, "group name is already existed");
                System.out.println("group name is already existed");
                break;
            }
        }
        if (listModel.toArray().length != 0 && !txtGroupName.getText().equals("") && !existedName) {
            //in sendGroup sender name must be added as a member name for recivers
            Group newgroup = new Group(txtGroupName.getText());
            Group sendGroup = new Group(txtGroupName.getText());
            for (Object object : listModel.toArray()) {
                newgroup.members.add((String) object);
                sendGroup.members.add((String) object);
            }
            Client.groubs.add(newgroup);
            tblHomeMsgsModel.addRow(new Object[]{"your "+txtGroupName.getText()+" name  group has been added "});

            // reset fileds
            txtGroupName.setText("");
            listModel.removeAllElements();
            cmbAddtoGroup.removeAllItems();
            addingEvent = true;
            for (String otherCleint : Client.otherCleints) {
                cmbAddtoGroup.addItem(otherCleint);
            }
            addingEvent = false;
            //update group combobox
            cmbGroups.addItem(newgroup.name);
            // add to my groubsCombobox
            cmbMygroubs.addItem(newgroup.name);
            cmbMyBillsgroubs.addItem(newgroup.name);
            cmbRecivedBillsgroubs.addItem(newgroup.name);
            //send group info to all members
            // add client name to groube members befor sending grop info to

            sendGroup.members.add(txtName.getText());
            Client.Send(sendGroup);

        } else {
            System.out.println("hata");
        }
    }//GEN-LAST:event_btnMakeGroupActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtBillDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBillDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBillDescriptionActionPerformed

    private void btnSendBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendBillActionPerformed
        // TODO add your handling code here:
        // if one group is selected and amount and  description is existed add bill
        if (Client.groubs.size() != 0 && !txtBillDescription.getText().equals("") && !txtBillAmount.getText().equals("")) {
           
            Bill newBill = new Bill((txtName.getText() + "-" + Client.billId), txtName.getText(), Double.parseDouble(txtBillAmount.getText()), 0.0, txtBillDescription.getText(),
                    Client.groubs.get(cmbGroups.getSelectedIndex()));
            Client.sendedBills.add(newBill);
         
            Client.Send(newBill);
            cmbMyBillsgroubs.setSelectedIndex(0);
            FillMyBillsTable("All");
            // add msg to home table
            tblHomeMsgsModel.addRow(new Object[]{"your "+txtName.getText() + "-" + Client.billId+" id  Bill has been added "});
            Client.billId++;
            txtBillAmount.setText("");
            txtBillDescription.setText("");
            ////////////////////////
            tblMyBillsDetailModel.setRowCount(0);;

        }

    }//GEN-LAST:event_btnSendBillActionPerformed

    private void cmbMygroubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMygroubsActionPerformed
        // TODO add your handling code here:
        // show grop members in list according to selected member
        if (cmbMygroubs.getSelectedIndex() != -1) {
            listMygroupsMemberModel.removeAllElements();
            for (Object object : Client.groubs.get(cmbMygroubs.getSelectedIndex()).members) {
                listMygroupsMemberModel.addElement(object);
            }
        }


    }//GEN-LAST:event_cmbMygroubsActionPerformed

    private void cmbGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGroupsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGroupsActionPerformed

    private void cmbMyBillsgroubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMyBillsgroubsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMyBillsgroubsActionPerformed

    private void cmbRecivedBillsgroubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRecivedBillsgroubsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRecivedBillsgroubsActionPerformed

    private void cmbMyBillsgroubsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMyBillsgroubsItemStateChanged
        // TODO add your handling code here:
       
        FillMyBillsTable(cmbMyBillsgroubs.getItemAt(cmbMyBillsgroubs.getSelectedIndex()));
    }//GEN-LAST:event_cmbMyBillsgroubsItemStateChanged
    public void filltblBilldetails() {
        // for selected bill show all related sub bills with paying status
        if (tblBills.getSelectedRow() != -1) {
            Bill selectedBill;
            tblMyBillsDetailModel.setRowCount(0);
            for (Bill sendedBill : Client.sendedBills) {
                if (tblBills.getValueAt(tblBills.getSelectedRow(), 5).toString()
                        .equals(sendedBill.id)) {
                    selectedBill = sendedBill;

                    for (int i = 0; i < selectedBill.reciver.members.size(); i++) {
                        tblMyBillsDetailModel.addRow(new Object[]{selectedBill.reciver.members.get(i),
                            selectedBill.amount / (selectedBill.reciver.members.size() + 1),
                            selectedBill.payingStatues.get(i)
                        });
                    }

                }
            }
        }
    }
    private void tblBillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBillsMouseClicked
        // TODO add your handling code here:
        filltblBilldetails();

    }//GEN-LAST:event_tblBillsMouseClicked

    private void btmMarkAsPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmMarkAsPaidActionPerformed
        // TODO add your handling code here:
        // if there is a selected sub bill and paying staues is not alreasdy true
        if (tblMyBillsDetail.getSelectedRow() != -1) {
            Bill selectedBill;
            /////
            for (Bill sendedBill : Client.sendedBills) {
                if (tblBills.getValueAt(tblBills.getSelectedRow(), 5).toString()
                        .equals(sendedBill.id.toString())) {
                    selectedBill = sendedBill;

                    for (int i = 0; i < selectedBill.reciver.members.size(); i++) {
                        if (selectedBill.reciver.members.get(i).equals(tblMyBillsDetail.getValueAt(tblMyBillsDetail.getSelectedRow(), 0).toString())) {
                            //sending message to person  who pay
                            if (selectedBill.payingStatues.get(i) != true) {
                                Message msg = new Message(Message.Message_Type.paid);
                                msg.content.add(selectedBill.id);
                                msg.reciverName = selectedBill.reciver.members.get(i);
                                Client.Send(msg);
                                selectedBill.payingStatues.set(i, true);
                                filltblBilldetails();
                                break;
                            } else {
                                System.out.println("alredy paid");
                            }
                        }
                    }

                }
            }
            ///

        }
    }//GEN-LAST:event_btmMarkAsPaidActionPerformed
    public void fillRecivedBilltable(String groupName) {
        // fill recived bill table according to paying statues
        try {
            tblRecivedBillsModel.setRowCount(0);

            if (groupName.equals("All")) {
               
                for (Bill recivedBill2 : Client.recivedBills) {
                    tblRecivedBillsModel.addRow(new Object[]{recivedBill2.sender, recivedBill2.amount, recivedBill2.description, recivedBill2.reciver.name, recivedBill2.reciver.members.size(),
                        recivedBill2.id, recivedBill2.ammountToPaid, recivedBill2.payingStatues.get(0)});
                }
            } else {

                 for (Bill recivedBill2 : Client.recivedBills) {
                   
                    if (recivedBill2.reciver.name.equals(groupName)) {
                        tblRecivedBillsModel.addRow(new Object[]{recivedBill2.sender, recivedBill2.amount, recivedBill2.description, recivedBill2.reciver.name, recivedBill2.reciver.members.size(),
                        recivedBill2.id, recivedBill2.ammountToPaid, recivedBill2.payingStatues.get(0)});
                    }
                }
            }
        } catch (Exception e) {
            // when there is no bills do nothing
        }
    }
    private void cmbRecivedBillsgroubsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbRecivedBillsgroubsMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbRecivedBillsgroubsMouseClicked

    private void cmbRecivedBillsgroubsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbRecivedBillsgroubsItemStateChanged
        // TODO add your handling code here:
        fillRecivedBilltable(cmbRecivedBillsgroubs.getItemAt(cmbRecivedBillsgroubs.getSelectedIndex()));
    }//GEN-LAST:event_cmbRecivedBillsgroubsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmMarkAsPaid;
    public javax.swing.JButton btnMakeGroup;
    private javax.swing.JButton btnSendBill;
    private javax.swing.JButton btnStart;
    public javax.swing.JComboBox<String> cmbAddtoGroup;
    public javax.swing.JComboBox<String> cmbGroups;
    public javax.swing.JComboBox<String> cmbMyBillsgroubs;
    public javax.swing.JComboBox<String> cmbMygroubs;
    public javax.swing.JComboBox<String> cmbRecivedBillsgroubs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserName1;
    public javax.swing.JList<String> listGroupMembers;
    public javax.swing.JList<String> listMygroupsMember;
    private javax.swing.JPanel panelBill;
    private javax.swing.JPanel panelGroup;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMybills;
    private javax.swing.JPanel panelMybills1;
    private javax.swing.JTable tblBills;
    private javax.swing.JTable tblHomeMsgs;
    private javax.swing.JTable tblMyBillsDetail;
    private javax.swing.JTable tblRecivedBills;
    private javax.swing.JTextField txtBillAmount;
    private javax.swing.JTextField txtBillDescription;
    private javax.swing.JTextField txtGroupName;
    public javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
